const resultado = {
    "diaDeSorte": {
      "mesDaSorte": "Maio",
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "07/11/2023",
      "dezenas": [
        "05",
        "11",
        "13",
        "15",
        "19",
        "20",
        "22"
      ],
      "numeroDoConcurso": 832,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "DIA_DE_SORTE",
      "valorEstimadoProximoConcurso": 1200000.0,
      "valorPremio": 0.0
    },
    "duplasena": {
      "dezenasSegundoSorteio": [
        "04",
        "08",
        "09",
        "14",
        "21",
        "24"
      ],
      "quantidadeGanhadoresSegundoSorteio": 0,
      "totalGanhadores": 0,
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "03/11/2023",
      "dataPorExtenso": "Sexta-feira, 03 de Novembro de 2023",
      "dataProximoConcurso": "06/11/2023",
      "dezenas": [
        "01",
        "15",
        "18",
        "27",
        "29",
        "46"
      ],
      "numeroDoConcurso": 2589,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "DUPLA_SENA",
      "valorEstimadoProximoConcurso": 400000.0,
      "valorPremio": 0.0
    },
    "federal": {
      "localSorteio": "ESPAÇO DA SORTE",
      "nomeMunicipioUFSorteio": "SAO PAULO, SP",
      "premios": [
        {
          "bilhete": "030970",
          "posicao": 1,
          "valorPremio": 500000.0
        },
        {
          "bilhete": "060451",
          "posicao": 2,
          "valorPremio": 27000.0
        },
        {
          "bilhete": "057539",
          "posicao": 3,
          "valorPremio": 24000.0
        },
        {
          "bilhete": "073185",
          "posicao": 4,
          "valorPremio": 19000.0
        },
        {
          "bilhete": "074141",
          "posicao": 5,
          "valorPremio": 18329.0
        }
      ],
      "acumulado": false,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "",
      "dezenas": [
        "030970",
        "060451",
        "057539",
        "073185",
        "074141"
      ],
      "numeroDoConcurso": 5814,
      "quantidadeGanhadores": 1,
      "tipoPublicacao": 3,
      "tipoJogo": "LOTERIA_FEDERAL",
      "valorEstimadoProximoConcurso": 0.0,
      "valorPremio": 500000.0
    },
    "loteca": {
      "resultadoJogos": [
        {
          "sequencia": 1,
          "equipeUm": "FORTALEZA",
          "equipeDois": "LDU",
          "siglaUFEquipeUm": "CE",
          "siglaUFEquipeDois": "",
          "golsEquipeUm": 1,
          "golsEquipeDois": 1,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "ECU"
        },
        {
          "sequencia": 2,
          "equipeUm": "CHAPECOENSE",
          "equipeDois": "TOMBENSE",
          "siglaUFEquipeUm": "SC",
          "siglaUFEquipeDois": "MG",
          "golsEquipeUm": 1,
          "golsEquipeDois": 0,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 3,
          "equipeUm": "ITUANO",
          "equipeDois": "MIRASSOL",
          "siglaUFEquipeUm": "SP",
          "siglaUFEquipeDois": "SP",
          "golsEquipeUm": 0,
          "golsEquipeDois": 0,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 4,
          "equipeUm": "PALMEIRAS",
          "equipeDois": "BAHIA",
          "siglaUFEquipeUm": "SP",
          "siglaUFEquipeDois": "BA",
          "golsEquipeUm": 1,
          "golsEquipeDois": 0,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 5,
          "equipeUm": "VILA NOVA",
          "equipeDois": "ATLETICO",
          "siglaUFEquipeUm": "GO",
          "siglaUFEquipeDois": "GO",
          "golsEquipeUm": 2,
          "golsEquipeDois": 1,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 6,
          "equipeUm": "ATLETICO",
          "equipeDois": "FLUMINENSE",
          "siglaUFEquipeUm": "MG",
          "siglaUFEquipeDois": "RJ",
          "golsEquipeUm": 2,
          "golsEquipeDois": 0,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 7,
          "equipeUm": "MANCHESTER UNITED",
          "equipeDois": "MANCHESTER CITY",
          "siglaUFEquipeUm": "",
          "siglaUFEquipeDois": "",
          "golsEquipeUm": 0,
          "golsEquipeDois": 3,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "ING",
          "siglaPaisDois": "ING"
        },
        {
          "sequencia": 8,
          "equipeUm": "ATHLETICO",
          "equipeDois": "SAO PAULO",
          "siglaUFEquipeUm": "PR",
          "siglaUFEquipeDois": "SP",
          "golsEquipeUm": 1,
          "golsEquipeDois": 1,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 9,
          "equipeUm": "GOIAS",
          "equipeDois": "VASCO DA GAMA",
          "siglaUFEquipeUm": "GO",
          "siglaUFEquipeDois": "RJ",
          "golsEquipeUm": 1,
          "golsEquipeDois": 1,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 10,
          "equipeUm": "NAPOLI",
          "equipeDois": "MILAN",
          "siglaUFEquipeUm": "",
          "siglaUFEquipeDois": "",
          "golsEquipeUm": 2,
          "golsEquipeDois": 2,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "ITA",
          "siglaPaisDois": "ITA"
        },
        {
          "sequencia": 11,
          "equipeUm": "AMERICA",
          "equipeDois": "GREMIO",
          "siglaUFEquipeUm": "MG",
          "siglaUFEquipeDois": "RS",
          "golsEquipeUm": 3,
          "golsEquipeDois": 4,
          "diaSemana": "Sábado",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 12,
          "equipeUm": "CORINTHIANS",
          "equipeDois": "SANTOS",
          "siglaUFEquipeUm": "SP",
          "siglaUFEquipeDois": "SP",
          "golsEquipeUm": 1,
          "golsEquipeDois": 1,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 13,
          "equipeUm": "LONDRINA",
          "equipeDois": "CRB",
          "siglaUFEquipeUm": "PR",
          "siglaUFEquipeDois": "AL",
          "golsEquipeUm": 1,
          "golsEquipeDois": 1,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        },
        {
          "sequencia": 14,
          "equipeUm": "VITORIA",
          "equipeDois": "JUVENTUDE",
          "siglaUFEquipeUm": "BA",
          "siglaUFEquipeDois": "RS",
          "golsEquipeUm": 0,
          "golsEquipeDois": 0,
          "diaSemana": "Domingo",
          "icSorteioResultado": 0,
          "siglaPaisUm": "BRA",
          "siglaPaisDois": "BRA"
        }
      ],
      "acumulado": false,
      "concursoEspecial": false,
      "dataApuracao": "30/10/2023",
      "dataPorExtenso": "Segunda-feira, 30 de Outubro de 2023",
      "dataProximoConcurso": "04/11/2023",
      "dezenas": null,
      "numeroDoConcurso": 1084,
      "quantidadeGanhadores": 1,
      "tipoPublicacao": 3,
      "tipoJogo": "LOTECA",
      "valorEstimadoProximoConcurso": 600000.0,
      "valorPremio": 436117.79
    },
    "lotofacil": {
      "acumulado": false,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "06/11/2023",
      "dezenas": [
        "01",
        "03",
        "04",
        "05",
        "10",
        "12",
        "13",
        "14",
        "15",
        "16",
        "19",
        "20",
        "23",
        "24",
        "25"
      ],
      "numeroDoConcurso": 2946,
      "quantidadeGanhadores": 2,
      "tipoPublicacao": 3,
      "tipoJogo": "LOTOFACIL",
      "valorEstimadoProximoConcurso": 1700000.0,
      "valorPremio": 750732.71
    },
    "lotomania": {
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "03/11/2023",
      "dataPorExtenso": "Sexta-feira, 03 de Novembro de 2023",
      "dataProximoConcurso": "06/11/2023",
      "dezenas": [
        "04",
        "07",
        "10",
        "13",
        "20",
        "22",
        "25",
        "27",
        "29",
        "33",
        "38",
        "44",
        "50",
        "62",
        "63",
        "71",
        "73",
        "75",
        "85",
        "91"
      ],
      "numeroDoConcurso": 2542,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "LOTOMANIA",
      "valorEstimadoProximoConcurso": 4400000.0,
      "valorPremio": 0.0
    },
    "maisMilionaria": {
      "trevosSorteados": [
        "3",
        "4"
      ],
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "08/11/2023",
      "dezenas": [
        "05",
        "08",
        "20",
        "33",
        "45",
        "49"
      ],
      "numeroDoConcurso": 92,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "MAIS_MILIONARIA",
      "valorEstimadoProximoConcurso": 93000000.0,
      "valorPremio": 0.0
    },
    "megasena": {
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "07/11/2023",
      "dezenas": [
        "13",
        "23",
        "26",
        "29",
        "45",
        "59"
      ],
      "numeroDoConcurso": 2652,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "MEGA_SENA",
      "valorEstimadoProximoConcurso": 9000000.0,
      "valorPremio": 0.0
    },
    "quina": {
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "06/11/2023",
      "dezenas": [
        "07",
        "09",
        "10",
        "57",
        "73"
      ],
      "numeroDoConcurso": 6283,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "QUINA",
      "valorEstimadoProximoConcurso": 3400000.0,
      "valorPremio": 0.0
    },
    "superSete": {
      "acumulado": false,
      "concursoEspecial": false,
      "dataApuracao": "03/11/2023",
      "dataPorExtenso": "Sexta-feira, 03 de Novembro de 2023",
      "dataProximoConcurso": "06/11/2023",
      "dezenas": [
        "4",
        "9",
        "0",
        "7",
        "4",
        "1",
        "0"
      ],
      "numeroDoConcurso": 467,
      "quantidadeGanhadores": 1,
      "tipoPublicacao": 3,
      "tipoJogo": "SUPER_SETE",
      "valorEstimadoProximoConcurso": 100000.0,
      "valorPremio": 8203359.85
    },
    "timemania": {
      "timeDoCoracao": "FLUMINENSE       /RJ",
      "acumulado": true,
      "concursoEspecial": false,
      "dataApuracao": "04/11/2023",
      "dataPorExtenso": "Sábado, 04 de Novembro de 2023",
      "dataProximoConcurso": "07/11/2023",
      "dezenas": [
        "11",
        "33",
        "40",
        "42",
        "45",
        "54",
        "57"
      ],
      "numeroDoConcurso": 2011,
      "quantidadeGanhadores": 0,
      "tipoPublicacao": 3,
      "tipoJogo": "TIMEMANIA",
      "valorEstimadoProximoConcurso": 23500000.0,
      "valorPremio": 0.0
    }
  }

  export default resultado;